"""Generate the canonical round-wire conductor catalog.

Bare AWG diameters use the exact ASTM B258 formula. Insulated (grade 1/2)
diameters come from catalog/conductors/insulation-round-wire.yaml, a draft
transcription of the IEC 60317-0-1 / NEMA MW1000 maximum-overall-diameter
tables that must be reviewed before it is trusted for production use.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from inductor_designer.domain.units import awg_bare_diameter_m

_CATALOG_REVISION = "round-wire-2"
_AWG_RANGE = range(10, 33)
_IEC_DIAMETERS_MM = (0.20, 0.25, 0.315, 0.40, 0.50, 0.63, 0.80, 1.00, 1.25, 1.60, 2.00, 2.50)
_INSULATION_PATH = Path("catalog/conductors/insulation-round-wire.yaml")


def _load_insulation(path: Path) -> dict[str, tuple[float, float]]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return {
        entry["name"]: (entry["grade1DiameterM"], entry["grade2DiameterM"])
        for entry in data["records"]
    }


def _record(
    name: str,
    standard: str,
    bare_diameter_m: float,
    source: str,
    insulation: dict[str, tuple[float, float]],
) -> dict[str, object]:
    grades = insulation.get(name)
    return {
        "name": name,
        "standard": standard,
        "bareDiameterM": round(bare_diameter_m, 9),
        "grade1DiameterM": grades[0] if grades else None,
        "grade2DiameterM": grades[1] if grades else None,
        "source": source,
        "catalogRevision": _CATALOG_REVISION,
        "reviewStatus": "draft",
        "reviewedBy": None,
    }


def generate_records(insulation_path: Path = _INSULATION_PATH) -> list[dict[str, object]]:
    insulation = _load_insulation(insulation_path)
    records = [
        _record(f"AWG {gauge}", "awg", awg_bare_diameter_m(gauge), "ASTM B258 formula", insulation)
        for gauge in _AWG_RANGE
    ]
    records.extend(
        _record(
            f"{diameter_mm:g} mm",
            "iec-60317",
            diameter_mm / 1000.0,
            "IEC 60317 nominal",
            insulation,
        )
        for diameter_mm in _IEC_DIAMETERS_MM
    )
    return sorted(records, key=lambda record: str(record["name"]))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("catalog/conductors/round-wire.yaml"),
    )
    args = parser.parse_args(argv)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    document = {"records": generate_records()}
    args.out.write_text(
        "# Generated by tools/generate_conductors.py — regenerate, do not hand-edit.\n"
        + yaml.safe_dump(document, sort_keys=False),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
