"""Generate the canonical round-wire conductor catalog.

Bare AWG diameters use the exact ASTM B258 formula. Insulated (grade 1/2)
diameters are intentionally null in Milestone 1: they gain a consumer in the
Milestone 2 packing engine, and the IEC 60317-0-1 maximum-overall-diameter
tables must be transcribed and reviewed before they carry values.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from inductor_designer.domain.units import awg_bare_diameter_m

_CATALOG_REVISION = "round-wire-1"
_AWG_RANGE = range(10, 33)
_IEC_DIAMETERS_MM = (0.20, 0.25, 0.315, 0.40, 0.50, 0.63, 0.80, 1.00, 1.25, 1.60, 2.00, 2.50)


def _record(
    name: str, standard: str, bare_diameter_m: float, source: str
) -> dict[str, object]:
    return {
        "name": name,
        "standard": standard,
        "bareDiameterM": round(bare_diameter_m, 9),
        "grade1DiameterM": None,
        "grade2DiameterM": None,
        "source": source,
        "catalogRevision": _CATALOG_REVISION,
        "reviewStatus": "draft",
        "reviewedBy": None,
    }


def generate_records() -> list[dict[str, object]]:
    records = [
        _record(f"AWG {gauge}", "awg", awg_bare_diameter_m(gauge), "ASTM B258 formula")
        for gauge in _AWG_RANGE
    ]
    records.extend(
        _record(f"{diameter_mm:g} mm", "iec-60317", diameter_mm / 1000.0, "IEC 60317 nominal")
        for diameter_mm in _IEC_DIAMETERS_MM
    )
    return sorted(records, key=lambda record: str(record["name"]))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("catalog/conductors/round-wire.yaml"),
    )
    args = parser.parse_args(argv)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    document = {"records": generate_records()}
    args.out.write_text(
        "# Generated by tools/generate_conductors.py — regenerate, do not hand-edit.\n"
        + yaml.safe_dump(document, sort_keys=False),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
